### PR TITLE
Feat/election

### PR DESCRIPTION
**Pull request by connor4312**
See this PR and comment for context: https://github.com/mixer/etcd3/pull/66#issuecomment-509421620

### CODE REVIEW

**Comment by connor4312** [comment]
cc @yujuiting @SimonSchick

**Comment by yujuiting** [comment]
@connor4312 sorry for late reply.
I didn't aware about cancellation mechanism you mentioned.
And using rxjs to handle event as a stream is a great idea.
Thanks for your curation!
I will review and follow your update today.

**Comment by yujuiting** [comment]
I have ever thought about handle event as stream through rxjs. rxjs is common in frontend to handle something like input event or React action. But seems not usual in backend. rxjs is powerful because of its operators and based on functional programming.
My only concern is that do we really need rxjs to handle event of election?
If need, dose rxjs only serve for this?
If rxjs is not a common way to handle event in backend. Is to use rxjs proper?

**Comment by petermelias** [comment]
Fwiw I think while the decision to use Rx interfaces to implement this is _interesting_, I'm not entirely sure adding Rx as a project dependency just for this feature is necessarily worth it unless there is a larger plan to adopt Rx across the whole project.

I say this because when I implemented this as a standalone extension/lib on top of this project (in 2018) it was straight forward to just use regular Node event handlers to manage all the weird little cases that leader election brings.

No real strong opinion, just adding context

**Comment by connor4312** [comment]
Going with the other PR

**Pull request closed without merging**
